version: "3"
services:
  app:
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - mysql

  mysql:
    platform: linux/amd64
    image: mysql:9.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development
      MYSQL_USER: dev
      MYSQL_PASSWORD: Uphillmountain123..
    ports:
      - "3306:3306"  
